apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod
  ports:
    - port: 80
    #  Quando definimos só o port ele assume que o target port é o mesmo do port ou seja esse caso 80
      nodePort: 30000
    #  Esse cara pode ter valores entre 30k até 39k
  